import Head from 'next/head'

export default function Home() {
  function handle() {
    const a = ''
    return a
  }
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Home</h1>
      </main>
    </>
  )
}
